config/routes.rb
Forx::Application.routes.draw do
  get ':username/:repo' => 'repos#index', as: 'repo', :constraints => { username: /.*/, repo: /.*/ }

  root 'welcome#index'

  post '/' => 'welcome#search', as: 'search'

end

app/models/github_repo.rb
require 'open-uri'

class GithubRepo < Struct.new(:name, :url, :user_avatar, :username, :stargazers, :last_commit_on, :last_issue_closed_on, :hub_repo, :important)
  def self.fetch(username, repo_name)
    repo = client.repo("#{username}/#{repo_name}")
    GithubRepo.from_hub_repo(repo, true)
  end

  def rated_forks
    forks_tree = self.forks.map { |t| self.class.from_hub_repo(t, t.full_name == self.name) }

    Ranker.rate_repos(*forks_tree)
  end

  def forks
    hash = Hash.new
    hash[self.name] = self.hub_repo
    forks = self.class.client.forks(self.name, sort: :watchers, per_page: 100)

    if self.hub_repo.parent != nil
      repo = GithubRepo.from_hub_repo(self.hub_repo.parent)
      forks += repo.forks
    end

    forks.each do |fork|
      hash[fork.full_name] ||= fork
    end

    hash.values
  end

  private
  def self.client
    Octokit::Client.new(client_id: ENV['GITHUB_CLIENT_ID'] || '806ddf84f1bea4feb43b',
                        client_secret: ENV['GITHUB_CLIENT_SECRET'] || '2d8e160bf6be8048827ae5012e2a6d08e119794e')
  end

  def self.avatar(repo_owner)
    identicon_url = URI::encode("https://identicons.github.com/#{repo_owner.login}.png")
    "http://www.gravatar.com/avatar/#{repo_owner.gravatar_id}?d=#{identicon_url}&s=420"
  end

  def self.from_hub_repo(repo, important = false)
    GithubRepo.new(repo.full_name, repo.html_url, avatar(repo.owner),
      repo.owner.login, repo.watchers, repo.pushed_at, repo.updated_at, repo, important)
  end
end

app/models/repository.rb
class Repository < Struct.new(:name, :url, :user_avatar, :username, :score, :important)
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/repos_controller.rb
class ReposController < ApplicationController
  rescue_from Octokit::NotFound, with: :repo_not_found

  def index
    repo = GithubRepo.fetch(params[:username], params[:repo])

    @repositories = repo.rated_forks
  end

  private
  def repo_not_found
    redirect_to root_url, flash: { danger: "No public repository is found. Maybe a typo? Try again." }
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def search
    user, repo = params[:repo].to_s.split('/')
    if user.present? && repo.present?
      redirect_to repo_path(user, repo)
    else
      flash[:danger] = "Is that even a repository? Try again."
      render :index
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def foo_pluralize(count, singular, plural)
    count == 1 ? singular : plural
  end

  # Public: Convert flash type (Rails) to either one of the available bootstrap
  # alert class names.
  #
  # flash_type - Flash type String (Rails).
  #
  # Returns bootstrap class String.
  def bootstrap_class_for flash_type
    case flash_type
    when :success
      "alert-success"
    when :danger
      "alert-danger"
    when :alert
      "alert-warning"
    when :notice
      "alert-info"
    else
      flash_type.to_s
    end
  end
end

app/views/application/_search_form.html.erb
<%= form_tag search_url, role: 'form' do %>
  <div class="input-group">
    <input autofocus="autofocus" name="repo" class="form-control input-lg" type="text" placeholder="<user>/<repository>">
    <span class="input-group-btn">
      <button type="submit" class="btn btn-primary btn-lg"><%= button_text %></button>
    </span>
  </div>
<% end %>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |type, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert <%= bootstrap_class_for(type) %>">
      <button class="close" data-dismiss="alert">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{type}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title).presence || "forx" %></title>

    <!-- <meta name="viewport" content="width=device-width, initial-scale=1.0"> -->

    <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap-theme.min.css">

    <link rel="stylesheet" href="//cdn.jsdelivr.net/animatecss/2.1.0/animate.min.css">

    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="//cdn.jsdelivr.net/html5shiv/3.6.2/html5shiv.js"></script>
      <script src="/assets/js/respond.min.js"></script>
    <![endif]-->
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <script src="//netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>
    <script src="/assets/js/jquery.typer.js"></script>

    <%= csrf_meta_tags %>
  </head>

  <body background="/assets/image/background.jpg" style="background-size: 100% auto;">

    <!-- Wrap all page content here -->
    <div id="wrap">

      <!-- Begin page content -->
      <div class="container">
        <div class="page-header" style="margin-top: 80px;">
          <% if params[:controller] == "welcome" %>
            <h1 class="animated tada"><a style="text-decoration: none; color: inherit;" href="/">forx</a></h1>
          <% else %>
            <h1><a style="text-decoration: none; color: inherit;" href="/">forx</a></h1>
          <% end %>
        </div>

        <div class="page-content">
          <div class="row">
            <div class="span12">
              <!--[if lt IE 7]>
                <div class="alert alert-danger">
                  <div class="chromeframe">Beware! You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> or <a href="http://www.google.com/chromeframe/?redirect=true">activate Google Chrome Frame</a> to improve your experience.</div>
                </div>
              <![endif]-->
            </div>
          </div>

          <%= yield %>
        </div>

      </div>
    </div>

    <div id="footer">
      <div class="container">
        <p class="text-muted credit text-center"><small>forx was built by <a href="http://github.com/kseniiaPelykh">Kseniia Pelykh</a>, <a href="http://github.com/as-cii">Antonio Scandurra</a> and <a href="http://github.com/exalted">Ali Servet Donmez</a> for 2013 Rails Rumble.<br /> <a href="mailto:team@forxin.mygbiz.com">Want to get in touch?</a></small></p>
      </div>
    </div>

    <script src="http://s0.railsrumble.com/banner.js" type="text/javascript"></script>
    <script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

      ga('create', 'UA-45006628-1', 'railsrumble.com');
      ga('send', 'pageview');
    </script>
  </body>

</html>

app/views/repos/index.html.erb
<div class="row" style="margin-bottom: 40px;">
  <div class="col-xs-12">
    <p class="lead" style="margin-bottom: 10px;">We explored all the awesome forks around <a href="http://github.com/<%= @repositories.first.name %>"><%= @repositories.first.name %></a> on GitHub and found out <%= foo_pluralize(@repositories.count, "nothing particularly interesting, apparently <strong>there's not much going on here</strong>, except the repository itself, <em>obviously</em>.".html_safe, "<strong>only the very interesting ones</strong>, just for you! The larger the circle, the more important the fork.".html_safe) %></p>
  </div>
</div>
<div class="row" style="position:relative" >
<div id = "repocontainer">
<% @repositories.each do |repo| %>

		<div class = "circlecontent" style = "position:relative; cursor: pointer">
			<div class="circle" data-repo="<%= repo.name %>">
					<div class="percentage"><%= repo.score.round %> %</div>
					<div class="repository" data-score="<%= repo.score %>" user-avatar = "<%= repo.user_avatar %>">
					
					<%# Other properties available: %>
					<%#  * repo.url %>
					<%#  * repo.user_avatar %>
					<%#  * repo.username %>
					</div>

			</div>
			<div class = "shadow" style="position:relative"></div>
		<div class ="repositoryname" style ="position:relative; font-size:12px; text-align:center;word-wrap: break-word;">
      <a href="https://github.com/<%= repo.name %>" target="_blank"><%= repo.name %></a>
    </div>
	</div>

<% end %>
</div>

  <script> draw() </script>

</div>
<div class="row" style="margin-top: 80px; margin-bottom: 20px;">
  <div class="col-xs-12">
    <%= render partial: 'search_form', :locals => {:button_text => "Do that again."} %>
  </div>
</div>

app/views/welcome/index.html.erb
<div class="row" style="padding-left: 60px; margin-bottom: 20px;">
  <div class="col-xs-12">
    <img src="/assets/image/logo.png" />
  </div>
</div>
<div class="row">
  <div class="col-xs-12">
    <p class="lead text-center">Enter a <a href="http://github.com">GitHub</a> repository name to see a dynamically generated fork analysis for the awesomeness around it!</p>
  </div>
</div>
<div class="row" style="margin-bottom: 5px;">
  <div class="col-xs-12">
    <%= render 'layouts/flash_messages' %>
    <%= render partial: 'search_form', :locals => {:button_text => "Go for it!"} %>
  </div>
</div>
<div class="row" style="padding-left: 10px;">
  <div class="col-xs-12">
    <p data-typer-targets='{
      "targets" : [
        "Try with pktck/ParsePy, for example…",
        "Try with kohsuke/hudson, for example…",
        "Try with jenkinsci/jenkins, for example…",
        "Try with CocoaPods/Specs, for example…",
        "Try with heroku/heroku-push, for example…",
        "Try with tonymillion/Reachability, for example…",
        "Try with mxcl/homebrew, for example…",
        "Try with github/hubot-scripts, for example…",
        "Try with jamesallardice/Placeholders.js, for example…",
        "Try with erica/NSDate-Extensions, for example…",
        "Try with escoz/QuickDialog, for example…"
      ]
    }' class="lead">Try with escoz/QuickDialog, for example…</p>
  </div>
</div>
<div class="row" style="margin-top: 40px; margin-bottom: 20px;">
  <div class="col-xs-12">
    <div style="border-bottom: 1px solid #eee; margin-bottom: 5px;">
      <h5 class="text-muted">What? Wait! Why?</h5>
    </div>
    <p class="text-muted"><a href="http://google.com">GitHub</a> is a powerful collaboration, code review, and code management platform for open source and private projects &mdash; as per their own description &mdash; and we couldn't agree more. That's awesome, but you know what? GitHub <a href="http://help.github.com/articles/fork-a-repo">forks</a> are even more interesting concept than the source management itself.</p>
    <p class="text-muted">Forks create a huge opportunity to everyone expressing themselves, free of restrictions of any kind: not happy? Just fork it! All of this data is also publicly available through the <a href="http://developer.github.com">API</a>.</p>
    <p class="text-muted">Where anyone would have simply seen a powerful tool to work with, we see profound greatness. We are utterly curious about where do all these forks go? How do they live their lives? Does anybody even care?!</p>
    <p class="text-muted">There are different forms to see forks (or repositories for that matter) on GitHub, but none of which can tell you what other great stuff is growing around: sometimes you will discover that someone else is just a better maintainer for a given piece of software and in some cases you will witness a whole new path that has been taken and it maybe a good time for a revolution. People get inspired by others and create even greater things that nobody would've imagined before. Sky is the limit here, truly…</p>
    <p class="text-muted"><strong>forx</strong> is a contributor app for <a href="http://railsrumble.com">2013 Rails Rumble</a> trying to answer these questions.</p>
  </div>
</div>
<script type="text/javascript">
  $(function () {
    $('[data-typer-targets]').typer();
  });
</script>